### PR TITLE
Fix filenames

### PR DESCRIPTION
**Pull request by Zottelchen**

### CODE REVIEW

**Comment by macharoni2** [comment]
what exactly did you do here?

**Comment by macharoni2** [comment]
ok nvm i see what's been done, do colons/question marks cause issues in filenames? seemed to be working just fine for me on the preview page, i checked that very thoroughly

**Comment by Zottelchen** [comment]
@macharoni2 Depends on the OS. Linux would not have a problem, but with Windows this repo could not be downloaded & edited locally. Web (editor) is no issue.

**Comment by macharoni2** [comment]
oh, right, forgot about that—will avoid those in the future, although we were thinking of renaming the mythoclast page to ??? for spoiler reasons so will have to find a workaround there.

**Pull request merged**
